### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by changemenemo** [warehouseman/xubuntu-x2go-phusion#2]
/tmp/file2r3kmt is not a public key file.
**\* /etc/my_init.d/add_ssh_env_keys.sh failed with status 1

**\* Killing all processes...

**Comment by changemenemo** [comment]
it's okey it was because I didn't use env var

**Comment by martinhbramwell** [comment]
In reply to issue #1 yesterday you said "And I don't know why but I can't start it anymore". Were environment variables the cause?  Are you still able to start it up?

**Comment by changemenemo** [comment]
yes I have succeeded to re-run it. 

> docker run -d --name desktop --hostname=something -e SSH_KEYS="$(cat ~/.ssh/id_rsa.pub)" -e USER_PWRD=my_pass -e SSH_USER=myass  x2go;

x2go is the name of the your image, I build it myself
that's my line and at first : `"$(cat ~/.ssh/id_rsa.pub)"` i didn't use that syntax... Since i'm not for the whole env var thing. I don't know whyyou use so much env var, is there a resaon? So it seems that this env var 

Maybe you could less use env var?

**Comment by martinhbramwell** [comment]
The point of the environment variables is to provide you with the flexibility you need to configure it as you please.  If you want to hard code them into a new Dockerfile that is derived...

`FROM warehouseman/xubuntu-x2go-phusion`

...you would have what you want, no?
